POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0MTg5MzAwOSwidXNlcklkIjoyfQ.bHVK-ZkNU7Bt9nVSC3nHX-qwm70Z1-PfC0hZvrkEIw0

{
    "title":"events",
    "description":"Just a test",
    "location": "Test site",
    "datetime": "2025-03-05T20:31:37Z"
}