POST http://localhost:8080/events
content-type: application/json

{
    "title":"Unauthorized test event",
    "description":"Another test event",
    "location": "Test site",
    "datetime": "2025-03-05T20:31:37Z"
}