PUT http://localhost:8080/events/2
content-type: application/json 

{
    "title":"updated title",
    "description":"New description",
    "location":"Tallinn",
    "datetime":"2025-03-05T20:31:37Z"
}